### ISSUE TITLE
Consider disabling Nextcloud Social by default

### ISSUE THREAD

**Issue by strugee** [osuosl-cookbooks/osl-nextcloud#17]
The flags introduced in a71eb8977764bbc7ab87cc8e81a812c45b742713 could be used to disable Social by default. This is a good idea because Social is extremely unmaintained and, even more importantly, [actually interferes with normal upgrades, even if it's disabled](https://github.com/nextcloud/social/issues/1871).

**Comment by ramereth** [comment]
@strugee this app doesn't seem to be installed by default so we can't add it to disable it.

**Comment by strugee** [comment]
Oh I was figuring that if admins manually installed it (perhaps if they're new to Nextcloud) then it would get autodisabled again. Now that I'm actually writing that out though, that seems like suuuuper confusing and vaguely hostile behavior from the system... maybe just a note in the docs I guess? Or just deal with it if it ever comes up? (Just dropping all the Social tables' indices fixed it for me.)

**Comment by strugee** [comment]
Closing since this issue seems to be addressing something that I guess isn't really a problem - feel free to reopen if you want
