### ISSUE TITLE
Run MIME type migrations automatically

### ISSUE THREAD

**Issue by strugee** [osuosl-cookbooks/osl-nextcloud#18]
From the admin overview page:

> One or more mimetype migrations are available. Occasionally new mimetypes are added to better handle certain file types. Migrating the mimetypes take a long time on larger instances so this is not done automatically during upgrades. Use the command `occ maintenance:repair --include-expensive` to perform the migrations.

We should just run this automatically.

**Comment by ramereth** [comment]
@strugee should get run during an upgrade, correct?

**Comment by strugee** [comment]
Yeah, I don't think it comes up otherwise. I can just let you know if it ever shows up again?
